s1="""GAGTAATCACGGACCTCCTCCAGACCCTGGTTGCTTGCTCTGCAGGTGCGCCTCCTGGGAGTGGTGTCCA
AGGGCCAGCCCACGCTGGTGGTGATGGAGCTGATGGCTCACGGAGACCTGAAGAGCTACCTCCGTTCTCT
GCGGCCAGAGGCTGAGGTAAGCTGCTTCGGGGGACCCAGCGGGGTACTCGGTGGAGCACCCGCTCCTGGC
CTCCTCGGATCCCAGTGCTGCTGAAACACCAACCCCGTGTTTCTGTTTTAGAATAATCCTGGCCGCCCTC
CCCCTACCCTTCAAGAGATGATTCAGATGGCGGCAGAGATTGCTGACGGGATGGCCTACCTGAACGCCAA
GAAGTTTGTGCATCGGGACCTGGCAGCGAGAAACTGCATGGTCGCCCATGATTTTACTGTCAAAATTGGA
GGTTCGTCTGGCTTTCTGCTTTGAAAACATAACGACCCAGGCCAGGTTTGATTTCAGAAGGAGGTCATAG
CTGGTTTCCTG"""

print("original seq :",s1)

s1=s1.replace("A","a").replace("T","A").replace("a","T")
s1=s1.replace("G","g").replace("C","G").replace("g","C")

print("complimentary seq :",s1)

print("reverse of complimentary seq:",s1[::-1])

