s1="""ATGCAAGTCGAACGGTAACAGGAAGCAGCTTGCTGCTTTGCTGACGAGTGGCGGACGGGTGAGTAATGTC
TGGGAAACTGCCCGGTGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCGCAAGACC
AAAGAGGGGGACCTTCGGGCCTCTTGCCACCGGATGTGCCCAGATGGGATTAGCTAGTTGGTGAGGTAAC
GGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGCCACACTGGAACTGAGACACGGTC
CAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCG
TGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGGATGTGGTTAATAACCATA
TTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTG
CAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCC
GGGCTCAACCTGGGAACTGCATTCGAAACTGGCAGGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGT
GTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGAC
GCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCT
ATTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAATAGACCGCCTGGGGAGTACG
GCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGA
TGCAACGCGAA"""

s=s1.replace("\n","")
print(s)

from Bio.Seq import Seq

s2=Seq(s)

prot=s2.translate()
l1=[]
for i in range(len(prot)):
    if(prot.startswith("*",i)):
       #print(i)
       l1.append(i)

print(l1)
print(prot[:l1[8]])
